# Generated by Django 5.1.1 on 2024-10-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sement_uz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.IntegerField(default=998)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sement_uz/images/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
