# Generated by Django 5.1.1 on 2024-10-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sement_uz', '0003_order_status_order_user_alter_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='requisites',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='sum',
            field=models.IntegerField(default=0),
        ),
    ]
